"""
Synthetic edge cases for unusual, boundary, and error-state scenarios.
"""

from datetime import datetime, timezone

SYNTHETIC_LABEL = "SYNTHETIC - not a real operational record"
NOW = datetime.now(timezone.utc).isoformat()

FLIGHT_EDGE_CASES = [
    {
        "id": "edge-flight-006",
        "callsign": "NOGPS1",
        "country": "Unknown",
        "lat": None,
        "lng": None,
        "altitude": 10000,
        "speed": 450,
        "heading": 90,
        "origin": None,
        "dest": None,
        "source": "Synthetic (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Missing GPS coordinates - map/UI must handle null lat/lng",
    },
    {
        "id": "edge-flight-001",
        "callsign": "AI000",
        "country": "India",
        "lat": 28.56,
        "lng": 77.10,
        "altitude": 0,
        "speed": 0,
        "heading": 0,
        "origin": "DEL",
        "dest": "DEL",
        "source": "Synthetic (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Ground or parked aircraft",
    },
    {
        "id": "edge-flight-002",
        "callsign": "EK999",
        "country": "UAE",
        "lat": 25.25,
        "lng": 55.36,
        "altitude": 15000,
        "speed": 580,
        "heading": 45,
        "origin": "DXB",
        "dest": "JFK",
        "source": "Synthetic (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Altitude above normal cruise ceiling",
    },
    {
        "id": "edge-flight-003",
        "callsign": "N/A",
        "country": "Unknown",
        "lat": 10.0,
        "lng": 10.0,
        "altitude": 9500,
        "speed": 450,
        "heading": 270,
        "origin": None,
        "dest": None,
        "source": "Synthetic (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Blank callsign",
    },
    {
        "id": "edge-flight-004",
        "callsign": "QF404",
        "country": "Australia",
        "lat": -33.94,
        "lng": 151.18,
        "altitude": 8000,
        "speed": 0,
        "heading": 180,
        "origin": "SYD",
        "dest": "NRT",
        "source": "Synthetic (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Airborne but speed is zero",
    },
    {
        "id": "edge-flight-005",
        "callsign": "LH360",
        "country": "Germany",
        "lat": 49.01,
        "lng": 2.55,
        "altitude": 11000,
        "speed": 490,
        "heading": 360,
        "origin": "CDG",
        "dest": "DEL",
        "source": "Synthetic (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Heading boundary value 360",
    },
]

ALERT_EDGE_CASES = [
    {
        "id": "edge-alert-001",
        "callsign": "UA007",
        "type": "Squawk 7700",
        "severity": "high",
        "airport": "JFK",
        "message": "Squawk 7700 general emergency declared near New York",
        "timestamp": NOW,
        "source": "Synthetic alert engine (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Maximum severity emergency squawk",
    },
    {
        "id": "edge-alert-002",
        "callsign": "SQ321",
        "type": "No Signal",
        "severity": "high",
        "airport": "SIN",
        "message": "No Signal for 32 minutes near Singapore",
        "timestamp": NOW,
        "source": "Synthetic alert engine (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Extended signal dropout",
    },
    {
        "id": "edge-alert-003",
        "callsign": "TK000",
        "type": "Route Divergence",
        "severity": "low",
        "airport": None,
        "message": "Minor route divergence with no nearby airport",
        "timestamp": NOW,
        "source": "Synthetic alert engine (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Null airport field",
    },
    {
        "id": "edge-alert-004",
        "callsign": "BA001",
        "type": "Altitude Anomaly",
        "severity": "medium",
        "airport": "LHR",
        "message": "Duplicate alert for same flight and type",
        "timestamp": NOW,
        "source": "Synthetic alert engine (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Duplicate emission",
    },
]

ROUTE_EDGE_CASES = [
    {
        "from": "DEL",
        "to": "DEL",
        "fromLat": 28.56,
        "fromLng": 77.10,
        "toLat": 28.56,
        "toLng": 77.10,
        "flights": 1,
        "source": "Synthetic (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Origin equals destination",
    },
    {
        "from": "GRU",
        "to": "NRT",
        "fromLat": -23.43,
        "fromLng": -46.47,
        "toLat": 35.77,
        "toLng": 140.39,
        "flights": 0,
        "source": "Synthetic (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Zero flights on route",
    },
    {
        "from": "DXB",
        "to": "LHR",
        "fromLat": 25.25,
        "fromLng": 55.36,
        "toLat": 51.47,
        "toLng": -0.46,
        "flights": 999,
        "source": "Synthetic (mock)",
        "SYNTHETIC_LABEL": SYNTHETIC_LABEL,
        "edge_case": "Extreme flight count for chart stress test",
    },
]
